-- MySQL Script generated by MySQL Workbench
-- Ср 13 янв 2021 03:45:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sklad
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sklad` ;

-- -----------------------------------------------------
-- Schema sklad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sklad` DEFAULT CHARACTER SET utf8 ;
USE `sklad` ;

-- -----------------------------------------------------
-- Table `sklad`.`units`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklad`.`units` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sklad`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklad`.`suppliers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `inn` DECIMAL(50) NOT NULL,
  `kpp` DECIMAL(50) NOT NULL,
  `contact_name` VARCHAR(255) NOT NULL,
  `telephone_number` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sklad`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklad`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `count` INT NOT NULL,
  `unit_id` INT NULL,
  `price` INT NOT NULL,
  `date_receipt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `supplier_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `units_id_idx` (`unit_id` ASC) VISIBLE,
  INDEX `supplier_id_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `unit_id`
    FOREIGN KEY (`unit_id`)
    REFERENCES `sklad`.`units` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `supplier_id`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `sklad`.`suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sklad`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklad`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `inn` DECIMAL(50) NOT NULL,
  `kpp` DECIMAL(50) NOT NULL,
  `contact_name` VARCHAR(255) NOT NULL,
  `telephone_number` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sklad`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklad`.`sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sum` INT NULL,
  `customer_id` INT NULL,
  `date_sale` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `sklad`.`customers` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sklad`.`sale_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sklad`.`sale_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NULL,
  `count` INT NOT NULL,
  `price` INT NOT NULL,
  `sale_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
  INDEX `sale_id_idx` (`sale_id` ASC) VISIBLE,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `sklad`.`products` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `sale_id`
    FOREIGN KEY (`sale_id`)
    REFERENCES `sklad`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
